# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
# ~> https://gitter.im/minicomp/wax/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'The Lost Pocketbook of John Williams'
description:      'A Minimal Look at the Consequences of Mutiny'
url:              ''
baseurl:          '/johnwilliams'
copyright:        'Creative Commons, 2021'
logo:             '/assets/logo.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
incremental: true
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  johnwilliams: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'johnwilliams_item' # the layout for the pages to use
    metadata:
      source: 'johnwilliams.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/johnwilliams' # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      johnwilliams:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - title
          - people
          - _date
          - revolutionary_date
          - location
          - language

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:

  - label: 'The Mutiny on the Danae'
    sub:
      - label: 'About the Case'
        link: '/about_johnwilliams/'
      - label: 'The Principal Characters'
        link: '/principal_characters/'
      - label: 'Timeline'
        link: '/timeline/'
  - label: 'Transcriptions'
    sub:
      - label: 'Letter to Adm. Board & Minute'
        link: '/transcriptions/letter_adm/'
      - label: 'Letter to Milbanke'
        link: '/transcriptions/letter_milbanke/'
      - label: 'Defence & Autobiography'
        link: '/transcriptions/defence_auto/'
      - label: 'Summary of the Case & Pardon'
        link: '/transcriptions/summary/'
      - label: 'Doc. 1 - Procurator'
        link: '/transcriptions/procurator/'
      - label: 'Doc. 2 - Passport, Bordeaux'
        link: '/transcriptions/passport_bordeaux/'
      - label: 'Doc. 3 - Money Owed, Prosecution'
        link: '/transcriptions/mo_prosecution'
      - label: 'Doc. 4 - US Protection Papers'
        link: '/transcriptions/passport_us/'
      - label: 'Doc. 5 - Passport, Bayonne'
        link: '/transcriptions/passport_bayonne/'
      - label: 'Doc. 6 - Money Owed, Corsair La Mouche'
        link: '/transcriptions/mo_corsair_lamouche/'
      - label: 'Doc. 7 - Money Owed, 26 Francs'
        link: '/transcriptions/mo_26francs'
  - label: 'Reference Library'
    sub:
      - label: 'The Devil Himself'
        link: '/devil_himself/'
      - label: 'The Danae Mutiny'
        link: '/danae_mutiny/'
      - label: 'The Naval Chronicle'
        link: '/naval_chronicle/'
      - label: 'Works on Other Mutinies'
        link: '/other_mutinies/'
  - label: 'About'
    sub:
      - label: 'About this Site'
        link: '/about/'
      - label: 'Documentation'
        link: 'https://minicomp.github.io/wiki/wax/'
      - label: 'Credits'
        link: '/credits/'
  - label: 'Browse'
    link: '/collection/'
  - label: 'Search'
    link: '/search/'
  - label: 'Reuse'
    link: '/reuse/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'GitHub'
      link: 'https://github.com/minicomp/wax'
    - label: 'Credits'
      link: '/credits'
    - label: 'Works Cited'
      link: '/works_cited/'
    - label: 'Contact'
      link: 'mailto:mwalker@mun.ca'
  logos:
    - img: '/img/logo.png'

# FIN
